stitch/src/androidTest/java/com/mongodb/stitch/StitchClientServiceTest.kt
stitch/src/main/java/com/mongodb/stitch/android/StitchClient.java
stitch/src/main/java/com/mongodb/stitch/android/auth/anonymous/AnonymousAuthProvider.java
stitch/src/main/java/com/mongodb/stitch/android/auth/apiKey/APIKeyProvider.java
stitch/src/main/java/com/mongodb/stitch/android/auth/custom/CustomAuthProvider.java
stitch/src/main/java/com/mongodb/stitch/android/auth/emailpass/EmailPasswordAuthProvider.java
stitch/src/main/java/com/mongodb/stitch/android/auth/oauth2/facebook/FacebookAuthProvider.java
stitch/src/main/java/com/mongodb/stitch/android/auth/oauth2/google/GoogleAuthProvider.java

These are pretty much the exact same changes as iOS.
**Drive-bys**:
- the static `AUTH_TYPE` property of each auth provider is now `public` instead of `private`
- when adding or removing keys from SharedPreferences, changes are applied in bulk rather than one at a time.

STITCH-1041 Improve semantics of multiple logins

---

stitch/src/androidTest/java/com/mongodb/stitch/StitchClientServiceTest.kt
stitch/src/main/java/com/mongodb/stitch/android/StitchClient.java
stitch/src/main/java/com/mongodb/stitch/android/StitchClientFactory.java

This is relatively straightforward, and functionally similar to the change in the iOS SDK. However there's no factory interface since we can't do static interface methods until Java 8, and there's also an additional `createFromProperties()` method on the factory class.

STITCH-1139 Android SDK: Create factory for clients

---

stitch/src/main/java/com/mongodb/stitch/android/StitchClient.java

This change sets the default volley timeout for requests from StitchClient to 15 seconds by always using a `DefaultRetryPolicy` with a 15000ms timeout when enqueuing requests.
Didn't add a test yet since I wasn't sure how we would do it without mocking long response times.
We could also add a method for users to set the default timeout on a `StitchClient`. let me know if we want to add this (May also be worthwhile to think about as something to standardize across the SDKs).

STITCH-1178 Set default volley timeout to 15 seconds

---

stitch/src/main/java/com/mongodb/stitch/android/auth/anonymous/AnonymousAuthProviderInfo.java

The FQ_NAME for the anon provider was wrong, so `getAuthProviders()` on the `StitchClient` always would return false for `.hasAnonymous()`.

fix FQ_NAME for anon provider

---

android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoClientIntTests.kt
android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncMongoClientIntTests.kt
core/admin-client/src/main/java/com/mongodb/stitch/core/admin/Resources.kt
core/admin-client/src/main/java/com/mongodb/stitch/core/admin/services/rules/RulesResources.kt
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/ChangeEvent.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/ChangeEventUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreSyncUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerTestContext.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncUnitTestHarness.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/BaseStitchIntTest.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestRunner.kt
server/services/mongodb-remote/src/test/java/com/mongodb/stitch/server/services/mongodb/remote/RemoteMongoClientIntTests.kt
server/services/mongodb-remote/src/test/java/com/mongodb/stitch/server/services/mongodb/remote/internal/SyncMongoClientIntTests.kt

See https://docs.google.com/document/d/1lvd02JFNI9Aa7Zely3xMJEct_N-HMn84tKIIhMq7Zes/ for more detailed information on the agreed design.
- Add additional logic for creating v2 rules for MongoDB. Make setting rules easier, which is handy for integration tests.

STITCH-1970 Optimize UPDATE and REPLACE to be $set and $unset

---

android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncMongoClientIntTests.kt
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/Sync.java
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncImpl.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/CoreSync.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreDocumentSynchronizationConfig.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreSyncImpl.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreDocumentSynchronizationConfigUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncUnitTestHarness.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/ProxySyncMethods.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestRunner.kt
server/services/mongodb-remote/src/main/java/com/mongodb/stitch/server/services/mongodb/remote/Sync.java
server/services/mongodb-remote/src/main/java/com/mongodb/stitch/server/services/mongodb/remote/internal/SyncImpl.java
server/services/mongodb-remote/src/test/java/com/mongodb/stitch/server/services/mongodb/remote/internal/SyncMongoClientIntTests.kt

The main addition of this ticket is the added method `resumeSyncForDocument`. A major secondary change is that the language for "frozen/thawed" has been switched to "paused/resumed". This is the documentation for this method:
```
/**
* A document that is paused no longer has remote updates applied to it.
* Any local updates to this document cause it to be resumed. An example of pausing a document
* is when a conflict is being resolved for that document and the handler throws an exception.
*
* @param documentId the id of the document to resume syncing
* @return true if successfully resumed, false if the document
*         could not be found or there was an error resuming
*/
boolean resumeSyncForDocument(@Nonnull final BsonValue documentId);
```
This method is proxied upwards from …

STITCH-2133 Add ability to unfreeze document via sync

---

android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncMongoClientIntTests.kt
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/ChangeEvent.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreDocumentSynchronizationConfig.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncUnitTestHarness.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestRunner.kt

This is a relatively small PR, but it was pretty tricky to get right. I tried to think of all the edge cases I could but I’d definitely appreciate careful eyes on this one.
I implemented the version filtering in such a way that it only has to happen when writing to the local collection. Any time we insert or update documents locally, or replace documents locally with a resolved doc, I filter out the version field (and if it’s already committed in the case of a local update, I revert that part of the update). With Eric’s new namespace locking, reads don’t have to worry about ever seeing a document with a version, since in an unlocked and recovered state, there shouldn’t ever be a document in the collection with a version.
Also for the sake of performance, I opted in some places to go with …

STITCH-1972 Prevent modification of version field

---

core/sdk/src/main/java/com/mongodb/stitch/core/auth/StitchUserProfile.java
core/sdk/src/main/java/com/mongodb/stitch/core/auth/internal/StitchUserProfileImpl.java
core/sdk/src/test/java/com/mongodb/stitch/core/auth/StitchUserProfileUnitTests.java
core/sdk/src/test/java/com/mongodb/stitch/core/auth/internal/model/StoreAuthInfoUnitTests.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerTestContext.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncUnitTestHarness.kt

This PR supplements our sync unit tests with tests that do the following
* Verifies that undo documents are never leaked when write operations complete successfully.
* Verifies that several failure scenarios are recovered properly.
* Verifies that pathological inputs unrelated to synchronized documents are not stored in the local synchronized collection.
In writing these tests, I found various bugs in the recovery logic that should now be fixed. Some documents were getting leaked, and rollbacks sometimes occurred when they shouldn't have.
Also did a drive-by change to expose the min age and max age in a user profile to be Strings rather than ints. This follows the recent change to the iOS SDK, and protects the SDK from min_age and max_age String inputs that don't represent integer values.

STITCH-2185 Fix various issues with sync recovery logic, and add unit tests

---

android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncMongoClientIntTests.kt
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestRunner.kt

Per our discussions in Slack, this fixes the R2L sync routine to not drop events when the remote event version and local pending write version are both empty. This helps prevent us from missing some events that may have happened when both the local and remote document had no version.
To make this work with our tests:
* I fixed an int test to produce a version so that a conflict wouldn't be raised
* I added an int test to test this behavior.
* I fixed two unit tests that now exhibit different behavior. (I still don't completely grasp why I had to make the changes I did, but I think the original tests were wrong and the old behavior was a bug)

STITCH-2257 Remote event w/ no version should conflict with pending write w/ no version

---

README.md
contrib/README.md
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt

Per our decision, this commit removes the ability to (in code) swap from R2L first to L2R first behavior and eliminates the resulting duplicate test sequences. This change complies with our updated specification and ameliorates the need to make sure that all behaviors work across both directional preferences. Neither preference offered significant advantage to end users and complicated the logic when versions were missing during synchronization, as versions are not persisted locally.

STITCH-2263 - Android SDK: Always run R2L synchronization first

---

README.md

Currently the SDK silently fails if not configured to work with ProGuard.
Having custom rules to be added in an applications proguard rules file. 
1. Keeps all classes and classes in subpackages as well subclass for the package `com.mongodb.client.model`. This is where there are `Filters` and `Updates` models. which should not be technically obfuscated. 
2. Keeps all classes and classes in subpackages as well subclass for the package `com.mongodb.stitch.core.auth.internal.models` and 
`com.mongodb.stitch.core.internal.net`. This contains request and response models
3. Keeps all classes and subclasses for the package `com.mongodb.embedded.capi.internal` This has the `CAPI` class which has JNI bindings. 
4. Keeps the class `com.mongodb.embedded.client.MongoEmbeddedSettings` 
5. Keeps all …

Adding ProGuard rules to README

---

README.md
contrib/bump_version.bash

This updates the destination to a stitch-sdks subdirectory on the
existing bucket so that docs.mongodb.com/stitch-sdks can find it.
(Not sure, this was specifically required by techops.)
Removes the /docs/ part which is arguably redundant now that it is
hosted on docs.mongodb.com.
Also updates the README for the new docs URL. Please publish
the docs and check that the new URL works.

DOCSP-3936 Push docs to docs.mongodb.com

---

.evg.yml
README.md
android/build.gradle
android/core/build.gradle
android/core/lib-proguard-rules.pro

This PR may be small but it took a while to figure out the right incantations for all these things :)
This PR does the following
* Adds a new `lib-proguard-rules.pro` to `android.defaultConfig.consumerProguardFiles` in the `stitch-android-core` library. This adds the rules necessary for an Android app using the SDK to be minified with Proguard correctly.
* Since it is a consumer ProGuard file, it means that any app APK or test APK that consumes this library (via our SDK for instance) and enables proguard minification will automatically apply these rules when running proguard. This does not run ProGuard on our SDK, since [libraries are not supposed to](https://stackoverflow.com/questions/10982344/is-proguard-cfg-needed-for-library-projects#10992604).
* This only applies to Android. I did …

STITCH-2340 ProGuard integration and testing

---

core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt

This addresses the user-reported but that causes an unwanted "polling" behavior when an ID is synced but the remote collection does not contain information about the document with the corresponding ID (or the document is not visible due to rules).

STITCH-2491 - Properly handle missing documents in DataSynchronizer

---

android/core/src/main/java/com/mongodb/stitch/android/core/auth/internal/StitchAuthImpl.java
android/coretest/src/androidTest/java/com/mongodb/stitch/android/core/StitchAppClientIntTests.kt
core/sdk/src/main/java/com/mongodb/stitch/core/StitchClientErrorCode.java
core/sdk/src/main/java/com/mongodb/stitch/core/auth/internal/AuthInfo.java
core/sdk/src/main/java/com/mongodb/stitch/core/auth/internal/CoreStitchAuth.java
core/sdk/src/test/java/com/mongodb/stitch/core/auth/internal/CoreStitchAuthUnitTests.java
server/core/src/main/java/com/mongodb/stitch/server/core/auth/internal/StitchAuthImpl.java
server/coretest/src/test/java/com/mongodb/stitch/server/core/StitchAppClientIntTests.kt

This should bring the Android multi-user logic to parity with the JS PR logic in https://github.com/mongodb/stitch-js-sdk/pull/216. 
Fixes made here include the following:
* various internal naming changes to be consistent with Android
* new doAuthenticatedRequest overload to do authenticated requests on behalf of another user to prevent many prepareAuthRequest calls
* adding `USER_NOT_FOUND` and `USER_NOT_LOGGED_IN` error codes
* storing the user list as an ordered map (LinkedHashMap) rather than a LinkedList
* persisting device id when there is no active user
* removing users when not logged in
* removing anonymous users when they are logged out
* handling user linking profile failure edge case 
* various changes to the order of logic in `CoreStitchAuth`
* various test changes

STITCH-2509 fix some logic issues with multi-user authentication

---

build.gradle

javadoc 11.0.2 (not 11.0.1) was reporting this error:
> Task :core:stitch-core-sdk:javadoc
javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
Specifying the source java version to javadoc makes this error go away.

Fix javadoc 11.0.2+ 'unnamed module' error by specifying the source flag

---

android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoClient.java
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection.java
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoDatabase.java
contrib/docs-examples/com/mongodb/stitch/android/core/StitchAppClient.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoClient.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection/count-Bson-RemoteCountOptions.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection/count-Bson.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection/count.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection/find-Bson.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoCollection/find.java
contrib/docs-examples/com/mongodb/stitch/android/services/mongodb/remote/RemoteMongoDatabase.java

This is based on https://github.com/mongodb/stitch-android-sdk/pull/109 -- please look at that one first.
Staged:
https://docs-mongodbcom-staging.corp.mongodb.com/stitch/bush/crud-flow/sdk/java/com/mongodb/stitch/android/core/StitchAppClient.html

DOCSP-4381 Revamp crud flow, add examples 

---

android/examples/snippets/build.gradle
android/examples/snippets/src/androidTest/java/com/mongodb/stitch/android/examples/snippets/RemoteMongoClientExamples.java
android/examples/snippets/src/androidTest/java/com/mongodb/stitch/android/examples/snippets/RemoteMongoCollectionExamples.java
android/examples/snippets/src/androidTest/java/com/mongodb/stitch/android/examples/snippets/RemoteMongoDatabaseExamples.java
android/examples/snippets/src/androidTest/java/com/mongodb/stitch/android/examples/snippets/StitchAppClientExamples.java
android/examples/snippets/src/androidTest/java/com/mongodb/stitch/android/examples/snippets/StitchAuthExamples.java
android/examples/snippets/src/main/AndroidManifest.xml
contrib/README.md
settings.gradle

These can be copied over to the contrib/docs-examples directory manually for now
upon change.
This adds a new module under the examples module called "snippets" which is
just a bunch of integration tests containing the code examples.

DOCSP-4911 Add code example snippets as integration tests

---

core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/HashUtils.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/HashUtilsUnitTests.kt

Changes hash calculation to use unsigned bytes so as to be conformant with Go and Swift

STITCH-2806 - Fix hash calculation to use unsigned bytes

---

android/services/mongodb-remote-perftests/build.gradle
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncL2ROnlyPerformanceTestDefinitions.kt
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncPerformanceIntTestsHarness.kt
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncPerformanceTestContext.kt
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncPerformanceTestUtils.kt
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncPerformanceTests.kt
android/services/mongodb-remote-perftests/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/performance/SyncR2LOnlyPerformanceTestDefinitions.kt
android/services/mongodb-remote-perftests/src/main/java/com/mongodb/stitch/android/services/mongodb/performance/OkHttpInstrumentedTransport.kt
android/services/mongodb-remote-perftests/src/main/java/com/mongodb/stitch/android/services/mongodb/performance/PerformanceTestingException.java
core/sdk/src/main/java/com/mongodb/stitch/core/StitchRequestErrorCode.java
core/sdk/src/main/java/com/mongodb/stitch/core/internal/net/OkHttpTransport.java
core/sdk/src/main/java/com/mongodb/stitch/core/internal/net/Transport.java

This pull request accomplishes the following: 
1. Defines the Remote To Local performance tests (intiailSync, disconnectReconnect, syncPass)
2. Adds changeEventPercentages as configurable option in evergreen / local.properties
3. Puts some utility functions in SyncPerformanceTestutils.kt
4. Makes some small changes to the L2R tests 
5. Drive-by fix for not sending out requests that are too large for stitch to handle

Java SDK: Create R2L scenario performance test definitions

---

core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java

Addresses the case where sometimes events are received before the local changes are applied by deferring the emission of the event to the write model container in a few places in the data synchronizer.

STITCH-2847 - delays event emission until local changes are applied

---

android/services/mongodb-remote/src/androidTest/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncMongoClientIntTests.kt
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/Sync.java
android/services/mongodb-remote/src/main/java/com/mongodb/stitch/android/services/mongodb/remote/internal/SyncImpl.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncConfigurationUnitTests.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/ProxySyncMethods.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestRunner.kt

This adds a test that will now pass due to Doug's changes. Also I drove by adding the original configure() method back in

STITCH-2847: Investigate document availability using sync.find() when change event is received

---

core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/CompactChangeEvent.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/UpdateDescription.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/internal/ResultDecoders.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/ConflictHandler.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/ConflictResolution.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/DefaultSyncConflictResolvers.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/ChangeEvents.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/CoreDocumentSynchronizationConfig.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizer.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DocumentVersionInfo.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/InstanceChangeStreamListener.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/InstanceChangeStreamListenerImpl.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/NamespaceChangeStreamListener.java
core/services/mongodb-remote/src/main/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/NamespaceSynchronizationConfig.java
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerCRUDUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerTestContext.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/DataSynchronizerUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/NamespaceChangeStreamListenerUnitTests.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/SyncUnitTestHarness.kt
core/services/mongodb-remote/src/test/java/com/mongodb/stitch/core/services/mongodb/remote/sync/internal/UpdateDescriptionUnitTests.kt
core/testutils/src/main/java/com/mongodb/stitch/core/testutils/sync/SyncIntTestProxy.kt

This is the big one. This updates the mobile sync codebase to use `watch` stream with compact events rather than traditional MongoDB change events. This required us to modify all code that operated on the assumption that `UPDATE` change events would have full documents.
This means that the DataSynchronizer now operates with `CompactChangeEvent`s when working with remote change events, and `ChangeEvent`s when working with local change events.
This meant changing all the unit tests and integration tests to use the new conflict handler, and to have remote events that are compact change events rather than full change events.
All unit tests and integration tests are passing locally, so any evergreen failure is likely to be an OOM error.
Notable Drive-Bys:
* The user-defined custom conflict …

STITCH-2718 use update description deltas in mobile sync

---

core/sdk/src/main/java/com/mongodb/stitch/core/internal/net/BaseStitchRequestClient.java
core/sdk/src/main/java/com/mongodb/stitch/core/internal/net/OkHttpTransport.java
core/sdk/src/main/java/com/mongodb/stitch/core/internal/net/Transport.java
core/sdk/src/test/java/com/mongodb/stitch/core/internal/net/StitchRequestClientImplUnitTests.java

streamFunction now only wraps errors that aren't StitchServiceExceptions. Drove-by some doc comments and nits.

STITCH-2945 don't wrap stream transport errors when they are Stitch service errors
